apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-pvc
spec:
  volumeName: postgres-user-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi